kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-retain
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-ssd
  replication-type: none
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexusdata
  labels:
    name: nexusdata
spec:
  storageClassName: standard-retain  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi

