apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-validator-cm
data:
  application: |
    spring:
      rabbitmq:
        host: rabbitmq-service

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: schema-validator-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: schema-validator
    spec:
      # Refer to the PVC created earlier
      volumes:
      - name: storage
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: minio-pv-claim
      containers:
      - name: schema-validator
        # Pulls the default Minio image from Docker Hub
        image: schema-validator:0.0.1-SNAPSHOT
        args:
        - server
        - /storage
        env:
        # Minio access key and secret key
        - name: RABBITMQ_DEFAULT_USER
          value: "USER123456"
        - name: RABBITMQ_DEFAULT_PASS
          value: "PASS123456"
        ports:
        - containerPort: 9000
          # This ensures containers are allocated on separate hosts. Remove hostPort to allow multiple Minio containers on one host
          hostPort: 9000
        # Mount the volume into the pod
        volumeMounts:
        - name: storage # must match the volume name, above
          mountPath: "/storage"
---
apiVersion: v1
kind: Service
metadata:
  name: schema-validator-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: schema-validator
