apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/anthonyikeda/DataStores/confluence"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluencehome
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
