version: '3'
services:
  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5228:5228/udp"
      - "5000:5000/tcp"
    networks: 
      - logging
  elasticsearch:
    image: elasticsearch:latest
    command: "elasticsearch -Enetwork.host=0.0.0.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks: 
      - logging
  kibana:
    build: kibana/
    ports:
      - "5601:5601"
    networks: 
      - logging

networks:
  logging:
    external: true
