apiVersion: apps/v1
kind: Deployment
metadata:
  name:  jira-server
  labels:
    name:  jira-server
spec:
  selector:
    matchLabels:
      app: jira
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
        - image:  anthonyikeda/jira:8.0.1
          name:  jira-server
          resources:
            requests:
              cpu: "20m"
              memory: "2G"
          ports:
            - containerPort:  8080
              name:  serverport
          env:
            - name: JIRA_HOME
              value: /data
          volumeMounts:
            - mountPath: /data
              name: jirahome
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
            "-instances=test-jira-232517:us-central1:jira-database=tcp:0.0.0.0:5432",
            "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: jirahome
          persistentVolumeClaim:
            claimName: jirahome
        - name: jiraconfig
          persistentVolumeClaim:
            claimName: jiraconfig
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      restartPolicy: Always
