kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-standard
  replication-type: none
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jirahome
  labels:
    name: jirahome_volume_claim
spec:
  storageClassName: slow  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jiraconfig
  labels:
    name: jiraconfig_volume_claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
