apiVersion: v1
kind: Service
metadata:
  name: jira-service
spec:
  type: LoadBalancer
  loadBalancerIP: '35.202.25.242'
  selector:
    app: jira
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jiraworld
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jira
