apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-home
  labels:
    name: data-home
spec:
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: data-home
    fsType: ext4
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-config
  labels:
    name: data-config
spec:
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: data-config
    fsType: ext4
  capacity:
    storage: 5Gi
