apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jirahome
  labels:
    name: jirahome_volume_claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jiraconfig
  labels:
    name: jiraconfig_volume_claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
